version: 3

excludeFiles:
  - "_test\.go$"

exclude:
  - test

components:
  ecs:
    in: ecs/**
  ecs-system:
    in: system
  ecs-component:
    in: component
  logger:
    in: log
  wrapping-functional:
    in:
      - snapshot
  dev-tools:
    in: .

deps:
  ecs:
    mayDependOn:
      - ecs
      - logger

  ecs-system:
    mayDependOn:
      - ecs
      - ecs-component

  ecs-component:
    mayDependOn:
      - ecs

  dev-tools:
    anyVendorDeps: true

  wrapping-functional:
    mayDependOn:
      - ecs
      - ecs-component
      - ecs-system
